<?php 
include('includes/common/head.php');
include('includes/common/header.php');
include('includes/sections/services.php');
include('includes/sections/portfolio.php');
include('includes/sections/about.php');
include('includes/sections/technologies.php');
include('includes/sections/team.php');
include('includes/sections/contact.php');
include('includes/common/footer.php');
include('includes/modal/modals.php');
?>
